export const websites = [
    {
      id: "hva",
      name: "HVA Website",
      domain: "highvolt.tech",
      repo: "HVA-Website-Frontend",
      owner: "HighVolt-Analytics",
      workflowFile: "deploy.yml",
      branch: "main",
      status: "Live",
      lastDeploy: "Successful",
    },
    {
      id: "quantum-agent",
      name: "Quantum Agent",
      domain: "quantumagent.com.au",
      repo: "QUANTUM-AGENT",
      owner: "HighVolt-Analytics",
      workflowFile: "deploy.yml",
      branch: "main",
      status: "Live",
      lastDeploy: "Successful",
    },
    {
      id: "quantum-edupass",
      name: "Quantum EduPass",
      domain: "quantumedupass.com",
      repo: "Quantum-Immigration",
      owner: "HighVolt-Analytics",
      workflowFile: "deploy.yml",
      branch: "main",
      status: "Live",
      lastDeploy: "Successful",
    },
    {
      id: "quantum-ledgerline",
      name: "Quantum Ledgerline",
      domain: "quantumledgerlink.com",
      repo: "Quantum-Ledgerline",
      owner: "HighVolt-Analytics",
      workflowFile: "deploy.yml",
      branch: "main",
      status: "Live",
      lastDeploy: "Successful",
    },
  ];